:bug: fix plugins.md formatting for docs
Can't build the docs because of the following:

docs/docs/packages/plugins.md

39.56 [webpackbar] ✔ Client: Compiled with some errors in 37.40s
39.56 [ERROR] Client bundle compiled with errors therefore further build is impossible.
39.56 Error: MDX compilation failed for file "/opt/docusaurus/docs/packages/plugins.md"
39.56 Cause: Unexpected lazy line in expression in container, expected line to be prefixed with `>` when in a block quote, whitespace when in a list, etc
39.56 Details:
39.56 {
39.56   "column": 1,
39.56   "message": "Unexpected lazy line in expression in container, expected line to be prefixed with `>` when in a block quote, whitespace when in a list, etc",
39.56   "line": 617,
39.56   "name": "617:1",
39.56   "place": {
39.56     "_bufferIndex": 0,
39.56     "_index": 10,
39.56     "line": 617,
39.56     "column": 1,
39.56     "offset": 21207
39.56   },
39.56   "reason": "Unexpected lazy line in expression in container, expected line to be prefixed with `>` when in a block quote, whitespace when in a list, etc",
39.56   "ruleId": "unexpected-lazy",
39.56   "source": "micromark-extension-mdx-expression",
39.56   "url": "https://github.com/micromark/micromark-extension-mdx-expression/tree/main/packages/micromark-extension-mdx-expression#unexpected-lazy-line-in-expression-in-container-expected-line-to-be-prefixed"
39.56 }
39.56
39.56 --------------------------